(* ::Package:: *)

(* ::Input:: *)
(*ClearAll["Global`*"]*)
(*(*Define the parameters*)*)
(*ba=0.90; (*Benefit of attack*)*)
(*bd=0.79; (*Benefit of defense*)*)
(*ca=0.51; (*Cost of attack*)*)
(*cd=0.20; (*Cost of defense*)*)
(*w=0.98(*Loss to the defender*)*)
(*v=0.26(*Probability of successful defense*)*)
(**)
(*fs=0.0; (*Probability of catching attacker for attack*)*)
(*fu=0.0; (*Fine to attacker for an attack attempt*)*)
(**)
(*(*Define the replicator dynamics equations*)*)
(*f1=\[Alpha](1-\[Alpha]) (-ca+ba-fs-ba*v*\[Beta]-v*fu*\[Beta]+v*fs*\[Beta]);*)
(*f2=\[Beta](1-\[Beta]) (bd-cd-bd*\[Alpha]+v*bd*\[Alpha]+v*w*\[Alpha]);*)
(**)
(*(*Compute the Jacobian matrix*)*)
(*J=D[{f2,f1},{{\[Beta],\[Alpha]}}];*)
(**)
(*(*Define the equilibrium points*)*)
(*equilibria={{0,0},{0,1},{1,0},{1,1}};*)
(**)
(*(*Compute eigenvalues at each equilibrium point and determine stability*)*)
(*Print["Eigenvalues at equilibrium points:"];*)
(**)
(*equilibriumMarkers=Table[eigs=Eigenvalues[J/. {\[Beta]->eq[[1]],\[Alpha]->eq[[2]]}];*)
(*Print["At (",eq[[2]],",",eq[[1]],") -> Eigenvalues: ",eigs];*)
(*(*Check stability:If all eigenvalues are negative,it is stable (black filled).Otherwise,it is unstable (white filled).*)*)
(*If[AllTrue[eigs,#<0&],{Black,Disk[eq,0.02]},{White,Disk[eq,0.02],Black,Circle[eq,0.02]}],{eq,equilibria}];*)
(**)
(*(*Compute the correct internal equilibrium using the given formulas*)*)
(*internalEq={\[Beta]->(ba-ca-fs)/(v*(ba-fs+fu)),\[Alpha]->(cd-bd)/(v*bd-bd+v*w)};*)
(**)
(*(*Check if internal equilibrium is valid (i.e.,within (0,1) range)*)*)
(*validInternalEq=0<internalEq[[1,2]]<1&&0<internalEq[[2,2]]<1;*)
(**)
(*If[validInternalEq,(*Compute eigenvalues at the internal equilibrium if it's valid*)eigsInternal=Eigenvalues[J/. internalEq];*)
(*Print["At internal equilibrium ",internalEq," -> Eigenvalues: ",eigsInternal];*)
(*(*Add the internal equilibrium point with red color and label*)AppendTo[equilibriumMarkers,{Red,Disk[{internalEq[[1,2]],internalEq[[2,2]]},0.02]}];*)
(*AppendTo[equilibriumMarkers,Text[Style[{"\[Alpha] = "<>ToString@NumberForm[internalEq[[2,2]],{3,2}], "\[Beta] = "<>ToString@NumberForm[internalEq[[1,2]],{3,2}]},Red,14],{internalEq[[2,2]],internalEq[[1,2]]},{-1.5,11.2}]];,*)
(*(*Otherwise,notify that no valid internal equilibrium exists*)Print["No valid internal equilibrium in (0,1) range."]];*)
(**)
(*(*Stream plot with equilibrium points*)*)
(*StreamPlot[{f2,f1},{\[Beta],0,1},{\[Alpha],0,1},PlotRange->{{-0.05,1.05},{-0.05,1.05}},FrameStyle->Directive[Black],FrameLabel->{Style["Frequency of Defence",22,FontFamily->"Arial",Black],Style["Frequency of Attack",22,FontFamily->"Arial",Black]},FrameTicksStyle->Directive[Black,FontFamily->"Arial",22],StreamStyle->{Black},Epilog->equilibriumMarkers]*)
(*(*file=Export["figure5b.svg",%,ImageResolution->300];*)
(*Print["Saved at: ",file];*)*)


Directory[]
